import { withEconomics } from "./scoring";
import type { HuntProduct } from "./types";

/**
 * Non-TR demo rows kept for other regions until those markets go live.
 * Each productUrl is a marketplace deep link for the SAME product type as
 * the title/photo (not a generic homepage or bare search dump).
 */
const DEMO_SEEDS: Array<Parameters<typeof withEconomics>[0]> = [
  {
    id: "ds-lamp",
    title: "Dokunmatik masa lambası",
    nameKey: "deskLamp",
    platform: "Shopify",
    path: "shopify",
    region: "eu",
    country: "de",
    risk: 22,
    demand: 71,
    saturation: 28,
    imageSrc: "/products/desk-lamp.jpg",
    productUrl: "https://www.amazon.de/dp/B0CWHDF7K1",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "CJ Dropshipping → Shopify DE",
    sellPrice: 29.9,
    buyPrice: 9.5,
  },
  {
    id: "ds-organizer",
    title: "Kablo düzenleyici set",
    nameKey: "cableOrganizer",
    platform: "AliExpress → Shopify",
    path: "dropship",
    region: "asia",
    country: "cn",
    risk: 18,
    demand: 64,
    saturation: 22,
    imageSrc: "/products/cable-organizer.jpg",
    productUrl: "https://www.amazon.com/dp/B0DJPV1TT9",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "AliExpress / Amazon US listing research",
    sellPrice: 14.9,
    buyPrice: 3.2,
  },
  {
    id: "ds-mug",
    title: "Sızdırmaz seyahat termosu",
    nameKey: "travelMug",
    platform: "CJ → Shopify",
    path: "dropship",
    region: "us",
    country: "us",
    risk: 24,
    demand: 68,
    saturation: 31,
    imageSrc: "/products/travel-mug.jpg",
    productUrl: "https://www.amazon.com/dp/B0FGJW5R8B",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "CJ Dropshipping → Shopify US",
    sellPrice: 24.9,
    buyPrice: 8.1,
  },
  {
    id: "amz-oa",
    title: "Kablosuz kulaklık",
    nameKey: "wirelessBuds",
    platform: "Amazon",
    path: "amazon",
    region: "us",
    country: "us",
    risk: 72,
    demand: 88,
    saturation: 78,
    imageSrc: "/products/wireless-buds.jpg",
    productUrl: "https://www.amazon.com/dp/B0BTYCRJSS",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "Amazon US FBA / wholesale",
    sellPrice: 49.9,
  },
  {
    id: "amz-eu",
    title: "Protein shaker",
    nameKey: "proteinShaker",
    platform: "Amazon",
    path: "amazon",
    region: "eu",
    country: "de",
    risk: 65,
    demand: 74,
    saturation: 66,
    imageSrc: "/products/protein-shaker.jpg",
    productUrl: "https://www.amazon.de/dp/B07D9G8QZM",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "Amazon DE FBA",
    sellPrice: 14.9,
  },
  {
    id: "noon-gadget",
    title: "Araç telefon tutucu",
    nameKey: "phoneMount",
    platform: "noon",
    path: "marketplace",
    region: "me",
    country: "ae",
    risk: 48,
    demand: 62,
    saturation: 44,
    imageSrc: "/products/phone-mount.jpg",
    productUrl: "https://www.amazon.ae/dp/B08L5FN5N7",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "noon / Amazon.ae listing research",
    sellPrice: 45,
  },
  {
    id: "tt-viral",
    title: "LED şerit ışık",
    nameKey: "ledStrip",
    platform: "TikTok Shop",
    path: "marketplace",
    region: "us",
    country: "us",
    risk: 69,
    demand: 91,
    saturation: 71,
    imageSrc: "/products/led-strip.jpg",
    productUrl: "https://www.amazon.com/dp/B08BJJLNSZ",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "TikTok Shop / Amazon US listing",
    sellPrice: 19.9,
  },
  {
    id: "shop-me",
    title: "Seyahat seccadesi",
    nameKey: "prayerMat",
    platform: "Shopify",
    path: "shopify",
    region: "me",
    country: "sa",
    risk: 26,
    demand: 55,
    saturation: 24,
    imageSrc: "/products/prayer-mat.jpg",
    productUrl: "https://www.amazon.ae/dp/B07Z5ZQK8R",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "CJ → Shopify SA",
    sellPrice: 79,
    buyPrice: 22,
  },
  {
    id: "shopee-asia",
    title: "Mini USB vantilatör",
    nameKey: "miniFan",
    platform: "Shopee",
    path: "marketplace",
    region: "asia",
    country: "sg",
    risk: 44,
    demand: 67,
    saturation: 49,
    imageSrc: "/products/mini-fan.jpg",
    productUrl: "https://www.amazon.sg/dp/B09V7ZQK1M",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "Shopee / Amazon SG listing research",
    sellPrice: 12.9,
  },
  {
    id: "amz-high",
    title: "Oyuncu koltuğu",
    nameKey: "gamingChair",
    platform: "Amazon",
    path: "amazon",
    region: "eu",
    country: "fr",
    risk: 84,
    demand: 82,
    saturation: 86,
    imageSrc: "/products/gaming-chair.jpg",
    productUrl: "https://www.amazon.fr/dp/B07ZGJ2J3R",
    dataMode: "demo",
    scoresMode: "heuristic",
    supplier: "Amazon FR FBA",
    sellPrice: 189,
  },
];

export const DEMO_PRODUCTS: HuntProduct[] = DEMO_SEEDS.map((s) =>
  withEconomics(s),
);
